a = set('0123456')
b = set('13579')
c = set('024689')

print('Пересечение')
print(a & b)
print(a & c)
print(b & c)
print('Объединение')
print(a | b)
print(a | c)
print(b | c)
print('Разность')
print(a - b)
print(b - a)
print(a - c)
print(c - a)
print(b - c)
print(c - b)
print('Cимметрическая разность')
print(a ^ b)
print(a ^ c)
print(b ^ c)
print('Декартовое произведение')
print([(i, j) for i in a for j in b])
print([(i, j) for i in a for j in c])
print([(i, j) for i in b for j in c])
